learning-and-edit-page
norvele/cardkeeper pull request #10
Opened 2024-03-08 09:02 UTC by Danny-Yellow

2024-03-08 12:34 UTC, Danny-Yellow commented on frontend/src/assets/emoji/brooding.svg
Смайлик экспортится с наполовину прозрачной рукой

2024-03-08 12:34 UTC, Danny-Yellow commented on frontend/src/components/business/DynamicDeckDisplay/DynamicDeckDisplay.tsx
> -      fetchCards();
Нужен ли тут еще запрос на получение карточек для отображения того, сколько их еще надо для появления новых стопок?

2024-03-08 12:34 UTC, Danny-Yellow commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
>      setFormIsReset(true);
formHasReset

2024-03-08 12:34 UTC, Danny-Yellow commented on frontend/src/API/CardApiService.ts
> +  public async forgotCard(id: string) {}
Хз какие должны быть запросы

2024-03-08 12:34 UTC, Danny-Yellow commented on frontend/src/pages/LearningPage/LearningPage.tsx
> +        title={title}
тогда если там убрать null, сделать title ||  ''

2024-03-08 12:34 UTC, Danny-Yellow commented on frontend/src/store/cardFormStore.ts
> +    const newCard = { ...$cardForm, id: `${Date.now()}` };
id устанавливается на сервере?

2024-03-08 12:36 UTC, Danny-Yellow commented on frontend/src/components/business/TopBar/TopBar.tsx
> +  title?: string | null;
убрать null и undefined

2024-03-10 02:41 UTC, norvele requested changes

2024-03-10 02:41 UTC, norvele commented on frontend/src/components/business/DynamicDeckDisplay/DynamicDeckDisplay.tsx
> +    navigate(`/learning/${deck.id}?title=${deck.name}`);
Тут title мы не должны передавать. На странице learning мы по deckId должны получить данные по колоде

2024-03-10 02:41 UTC, norvele commented on frontend/src/components/business/DynamicDeckDisplay/DynamicDeckDisplay.tsx
> -      fetchCards();
хороший вопрос, думаю добавлю в ответ на запрос до стопок. С бэка будет приходить что типа:
```
{
  items: IDeck[],
  additional: {
    numberOfCardsToOpenMoreDecks: number,
  },
  pagination: {...} // на будущее
}
```
все ответы для списков будут одинаковые примерно такого формата

2024-03-10 02:41 UTC, norvele commented on frontend/src/assets/emoji/brooding.svg
кек, пока забей, сходу не удалось разобраться чо там, потом поправлю

2024-03-10 02:41 UTC, norvele commented on frontend/src/components/business/CardPageLayout/CardPageLayout.tsx
> +  rightButtonDisabled: boolean;
Я бы не стал тут ничо переименовывать, мы же не извне управляем что за кнопка будет слева что справа. Компоненты сверху (createCardPage и editCardPage) не знают какая кнопка слева, какая справа, потому что не они их назначают и получается нам типа не важно какая кнопка справа - главное что она справа, но это не так, нам важно что это кнопка сохранения

2024-03-10 02:41 UTC, norvele commented on frontend/src/components/business/Deck/Deck.tsx
> +  onClick: (_group: string) => void;
_group лишнее

2024-03-10 02:41 UTC, norvele commented on frontend/src/components/business/LearningPanel/LearningPanel.tsx
> +  isFliped: boolean;
flipped (с двумя pp)

2024-03-10 02:41 UTC, norvele commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
>      setFormIsReset(true);
hasBeenReset. Но вообще я не совсем понимаю зачем formIsReset нужен. В EditCardPage мы чуть подругому и проще делаем же, просто дергаем евент resetCardForm();

2024-03-10 02:41 UTC, norvele commented on frontend/src/pages/LearningPage/LearningPage.tsx
> +  const title = searchParams.get('title');
тут мы возьмем из роута deckId и сходим в апи чтобы получить данные по коллоде

2024-03-10 02:41 UTC, norvele commented on frontend/src/store/cardFormStore.ts
> +    const newCard = { ...$cardForm, id: `${Date.now()}` };
да, для post запросов id не будет с фронта прилетать, для patch он обязателен

2024-03-10 02:41 UTC, norvele commented on frontend/src/store/cardFormStore.ts
> +export const $cardSide = createStore<ICardSide>('front')
С буквой I в начале обознаются интерфейсы вроде как, у нас не интерфейс, просто CardSide

2024-03-10 02:41 UTC, norvele commented on frontend/src/store/cardsStore.ts
Надо бы переименовать в learningStore

2024-03-10 02:41 UTC, norvele commented on frontend/src/store/cardsStore.ts
> +  data: ICard | null;
в сторе будет храниться текущая карточка и инфа о стопке

2024-03-12 12:32 UTC, Danny-Yellow commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
>      setFormIsReset(true);
Видимо ты не понял мою логику. В предыдущем пр я использовал useState для cardSide. Сделал я так, потому при заходе на страницу форма ресетиться и соответственно, если пользователь вернулся назад и оставил свитчер в положении 'back', то показывается анимация того как свитчер возвращается в положение 'front'. Но ты сказал, что состояние cardSide лучше оставить в сторе. Тогда я создал formIsReset, чтобы компонент рендерился уже после того как форма полностью ресетнится и cardSide уже будет в положении 'front'
В editCardPage formIsReset нет, потому что сторона приходит из learningPage.
Не знаю норм так делать или нет. + в таком подходе есть проблема, что компонент рендериться не сразу, и есть микро подгруз

2024-03-13 03:11 UTC, norvele requested changes

2024-03-13 03:11 UTC, norvele commented on frontend/src/API/CardApiService.ts
> +      deck: {},
cardApi только карточку будет возвращать
deckApi только дек

2024-03-13 03:11 UTC, norvele commented on frontend/src/pages/LearningPage/LearningPage.tsx
> +  const openedDeck = useUnit($openedDeck);
openedDeck должен лежать тоже в сторе learningStore.

У нас будет страница редактирования колоды, и ты опять захочешь создать какойнить openedDeck, но в котором будет храниться инфа о редактируемой колоде. Предыдущий ты захочешь переименовать в openedDeckForLearning и осознаешь что его надо в learningStore выносить

2024-03-13 03:11 UTC, norvele commented on frontend/src/pages/LearningPage/LearningPage.tsx
> +  const openedDeck = useUnit($openedDeck);
В нашем случае сторы надо формировать по бизнес фичам (отображение колод, редактирование карточки, редактирование колоды, обучение и т.д.), это почти равно страницам, но это у нас так вышло.

Сторы по сущностям это больше какбудтобы про DomainDrivenDevelopment, но там подход другой вообще. Типа у нас были бы сторы cardStore, deckStore, в них бы по ID хранились сущности, а learningStore бы был над этими двумя и у себя хранил бы просто ID деки и карточки, чтобы найти их в своих сторах. В этом есть свои плюсы типо нормализации данных и что сущность если меняется то это моментально аффектит на всех кто ее использует, но и много своего гемороя.
В нашем случае это супер избыточно и плюсов не даст

2024-03-13 03:34 UTC, norvele commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
>      setFormIsReset(true);
да, я походу просмотрел, щаз понял. Ну крч был костыль с cardSide в компоненте, сейчас по сути он же тока называется formHasBeenReset ), но костылем это не перестало быть.

Короче я вроде уже говорил, но нужен один механизм для загрузки страниц или кусков страниц. Либо на уровне роутера либо компонентом оберткой или и то и другое. Короче суть в том чтобы мы могли говорить что для этой вот страницы или этого блока нужно выполнить такую асинхронную функцию, и пока она не выполнится - страница или блок не будет показаны (будет лоадер крутиться)
* для страницы createCardPage в этой функции будет сброс формы
* для editCardPage - сброс формы + загрузка данных карточки по ID
* для learningPage - загрузка данных колоды по ID + загрузка данных карточки

Давай попробуем это сделать не в этом ПР а в следующем, отдельно типо.

2024-03-13 03:39 UTC, norvele commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
>      setFormIsReset(true);
> В editCardPage formIsReset нет, потому что сторона приходит из learningPage.

там из learningPage ничо не приходит вроде, и по логике не должно

> компонент рендериться не сразу, и есть микро подгруз

ну от этого никуда не деться в неидеальном мире, подгрузы будут всегда ) обычно на это либо забивают либо маскируют\сглаживают всякими техниками

2024-03-20 01:24 UTC, norvele approved these changes, later dismissed

2024-03-26 13:19 UTC, norvele approved these changes

2024-03-28 04:24 UTC, merged