Reused deck settings store
norvele/cardkeeper pull request #17
Opened 2024-06-09 09:22 UTC by Danny-Yellow

2024-06-10 15:06 UTC, norvele commented on frontend/src/store/deckSettingsStore.ts
> +export const $textInputValue = createStore<string>('')
Наличие вот этого очень сильно смущает, мы сейчас вынесли получается вообще все из настроек колод и положили в 1 место, но настройки всежеразные, гдето есть текстовое поле с 1 логикой, гдето текстовое поле с другой гдето будет вообще какиенить кучеряво сложные настройки и это все превратится в мешанину

Я планировал вынести только логику связанную со списком, она +- одинаковая.

2024-06-10 15:24 UTC, norvele commented on frontend/src/store/deckSettingsStore.ts
> +export const $textInputValue = createStore<string>('')
т.е. получается должен быть стор для списка со скоупами под разные страницы (звучит тоже както неочень) и сторы под каждую конкретную страницу настроек со своей обособленной логикой

и пока чето я ваще сомневаюсь что мы делаем правильно это через скоупы т.к. наступит момент когда нам понадобится в 1 месте одновременно несколько скоупов...

короче надо поизучать код других приложений размером больше тудулиста, почитать внимательно доку (там есть еще какието домены и гейты) и подумать как сделать хорошо, кажется мы не понимаем чего-то в идеологии еффектора. Ну или забить хер на него и написать на редакс тулките, там точно опыта у комьюнити сильно больше

2024-06-22 07:54 UTC, norvele requested changes

2024-06-22 07:54 UTC, norvele commented on frontend/src/components/business/MiniCardList/MiniCardList.tsx
>      if (mode === 'normal') resetSelectedCards();
Вот этой логики тут не должно быть, вообще использований чего угодно из этого не должно тут быть, т.к. компонент не относится только лишь к all cards
```
import {
  $selectedCards,
  resetSelectedCards,
  selectCard,
  unSelectCard,
} from '@/store/allDeckSettingsStore';
```

Должна быть пропса selectedProps, и кэлбэк например toggleCardSelection. А ресет просто на страницу унести, для него кэлбэк не нужен

2024-06-22 07:54 UTC, norvele commented on frontend/src/pages/AllDeckSettingsPage/AllDeckSettingsPage.tsx
> +        deckId: 'recentlyAdded',
Тут во1 ошибка, во2 надо объединить эти фетчи в какойто 1 метод, например
```
const fetch = () => {
  fetchSearchedCards({
    deckId: 'all',
    limitCards,
    currentPage,
    value: textInputValue,
  });
}
```
и этот fetch() просто вызывать во всех нужных местах. таким образом мы будем иметь 1 место где мы настраиваем как делать запрос и ошибок не будет

2024-06-22 07:54 UTC, norvele commented on frontend/src/pages/AllDeckSettingsPage/AllDeckSettingsPage.tsx
> +    (async () => {
не понятно зачем обернуто в async, внутри всеравно await нет )

2024-06-22 07:54 UTC, norvele commented on frontend/src/pages/AllDeckSettingsPage/AllDeckSettingsPage.tsx
> +      {mode === 'normal' && (
Тут много копипасты, давай заменим на
```
const isNormalMode = mode === 'normal';

  return (
    <>
      <DeckSettingsLayout
        TopBar={
          <TopBar
            leftSlot={
              <IconButton
                variant="primary"
                size="small"
                onClick={isNormalMode ? onClickGoToBack : onClickCancel}
              >
                {isNormalMode ? (
                  <ArrowBackIcon />
                ) : (
                  <>
                    <CloseIcon />
                    <p>{selectedCards.length}</p>
                  </>
                )}
              </IconButton>
            }
            title={isNormalMode ? 'All Cards' : ''}
            rightSlot={
              isNormalMode ? (
                <IconButton variant="primary" size="small">
                  <AddIcon />
                </IconButton>
              ) : (
                <IconButton
                  variant="primary"
                  size="small"
                  color="red"
                  onClick={onClickDeleteFewCards}
                >
                  <DeleteIcon />
                </IconButton>
              )
            }
          />
        }
      >
        <TextInput
          textSize="normal"
          placeholder="Search"
          icon={<SearchIcon />}
          onChange={onChangeTextInput}
          value={textInputValue}
        />
        <main className={styles.main}>
          <MiniCardList
            mode={mode}
            cardList={cardList}
            cardsIsLoading={cardsIsLoading}
            currentPage={currentPage}
            totalPageCount={totalPageCount}
            onClickMore={cachedOnClickMore}
            onNextPage={onNextPage}
          />
        </main>
        {cardsIsLoading && <MiniCardSkeleton count={20} />}
      </DeckSettingsLayout>
    </>
  );
  ```

2024-06-23 16:24 UTC, Danny-Yellow commented on frontend/src/pages/AllDeckSettingsPage/AllDeckSettingsPage.tsx
> +    }, 550);
Не знаю нужна ли в этом компоненте всё-таки обертка fetch, мб там оставить, а тут сделать без нее
Я сюда эту логику перенес из useEffect, потому что там оказывается из-за дебаунса через некоторое время еще раз запрос отправлялся. Можно было сделать так, чтобы useEffect игнорировал монтирование, но при этом обновлялся при изменении зависимости, но я думаю лучше перенести всё в эту функцию
Со страницей там проблема в том, что несмотря на resetCardList, который ставит currentPage в единицу, fetch не успевает уловить эту инфу и использует предыдущее состояние, то же самое с value, поэтому приходится вот так прокидывать аргументы

2024-06-24 15:37 UTC, norvele approved these changes

2024-06-24 15:44 UTC, merged