create-and-edit-page
norvele/cardkeeper pull request #7
Opened 2024-01-18 12:02 UTC by Danny-Yellow

2024-01-21 07:27 UTC, norvele requested changes

2024-01-21 07:27 UTC, norvele commented on frontend/src/components/UI/buttons/button/button.module.scss
> +  svg {
Тут нарушаем инкапсуляцию, кнопка не знает что иконки у нас свг и темболее что иконки сделаны как path с fill, к примеру иконка может быть сделана бордерами или еще как-то.

В ксс есть переменная currentColor, свг тоже поддерживает эту фичу и внутри свг можно написать fill="currentColor" например. Тогда в ксс цветом иконки мы можем управлять также как цветом текста

2024-01-21 07:27 UTC, norvele commented on frontend/src/components/business/ButtonGroup/buttonGroup.module.scss
> +hr {
Я не уверен как работают ксс модули, но этот стиль не станет глобальным?

2024-01-21 07:27 UTC, norvele commented on frontend/src/components/business/Form/Form.tsx
> +      <Modal
Так мы быстро упремся в ситуацию когда не сможем показать модалку из-за стилей. Допустим у нас компонент имеет свой z-index или position или обрезается както и модалка физически не сможет показаться выше всех элементов на экране.

Нужен механизм, который бы показывал модалки всегда где-то на верхнем уровне дерева компонентов.

2024-01-21 07:27 UTC, norvele commented on frontend/src/components/business/Form/Form.tsx
У компонента слишком абстрактное название, надо хотя бы CardForm

2024-01-21 07:27 UTC, norvele commented on frontend/src/components/business/Form/Form.tsx
> +  onChangeCheckboxHandler: () => void;
Слишком абстрактное название, не checkbox, а canBeInFocusedCheckbox. Чекбоксов может быть много в будущем

2024-01-21 07:27 UTC, norvele commented on frontend/src/components/business/Form/Form.tsx
> +      <TopBar
Выглядит сомнительно, что у нас хедер в форме. Надо либо с названием компонента этого подумать либо еще 1 уровень абстракции делать CreateCardPage -> CardPageLayout -> CardForm. Только CardForm должен приходить в CardPageLayout как чайлд. А CardPageLayout  рисует по сути хедер и чайлда

2024-01-21 07:27 UTC, norvele commented on frontend/src/components/business/Card/Card.tsx
Я бы переименовал в какойнить CardEditor, т.к. это не просто карточка, а мы имеем там свичер и текстарию

2024-01-21 07:27 UTC, norvele commented on frontend/src/components/business/Card/Card.tsx
> +  useEffect(() => {
Не сразу понял что за emptySide и я так понял это чтобы при валидации переключать сторону карточки. Слово empty не нужно, оно вводит в заблуждение.

локальный стейт const [side, setSide] = useState<'front' | 'back'>('front'); не нужен. У нас стейт должен быть выше, по хорошему вообще в сторе. Достаточно просто пропс side и setSide

2024-01-21 07:27 UTC, norvele commented on frontend/src/components/business/Card/Card.tsx
> +        <TextareaAutosize
Автосайз тут лишний, можно просто текстарию по размеру карточки, внутри будет скролл если не помещается текст

2024-01-21 07:27 UTC, norvele commented on frontend/src/components/business/Card/Card.tsx
> +    _side: 'frontText' | 'backText',
если у нас уже есть понятие side которое 'front' | 'back', то лучше использовать его же, если суть та же самая

2024-01-21 07:27 UTC, norvele commented on frontend/src/components/business/Card/Card.tsx
> +    _side: 'frontText' | 'backText',
И вот это лишнее уберется const sideText = side === 'front' ? 'frontText' : 'backText'; и inputValue

2024-01-21 07:27 UTC, norvele commented on frontend/src/components/business/Card/Card.tsx
> +    _event: React.ChangeEvent<HTMLTextAreaElement>,
надо бы вместо сырого евента слать просто стрингу с тем что мы написали. Потому что в теории у нас может вместо текстарии быть что-то другое, может визинг редактор который будет слать другой евент или вообще не слать. Короче суть в том что коду выше пофиг на все кроме текста который мы написали, этот компонент всю логику по получению этого текста должен инкапсулировать в себе

2024-01-21 07:27 UTC, norvele commented on frontend/src/components/business/Card/Card.tsx
> +  variant: 'primary' | 'secondary';
а для чего эта пропса?

2024-01-21 07:27 UTC, norvele commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
> +  const [newCard, setNewCard] = useState<ICard>({
весь стэйт нужно вытащить в стор

2024-01-21 07:27 UTC, norvele commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
> +  const [newCard, setNewCard] = useState<ICard>({
давай еще сделаем CardApiService и ApiService который используется в CardApiService

- В ApiService будут вызовы запросов к бэку, типа наша обертка над fetch. Там мы сможем например автоматом подставлять auth токен
- CardApiService это обертка над ApiService для домена Карточка, т.е. там будут методы по типу fetchCard, createCard, editCard и т.д. Этот сервис будет знать про то какие запросы для карточки есть на бэке и уметь их делать. Также мы сможем просто мокнуть метод fetchCard, который отдаст нам данные через таймаут, чтобы эмулировать бэк пока его нету

2024-01-21 07:43 UTC, norvele commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
> +  const [newCard, setNewCard] = useState<ICard>({
Сюда же, надо поисследовать как в реакте грузить данные требуемые для страницы. Т.е. мы заходим на роут - где-то мы понимаем что нам нужны определенные данные (в самом роуте или компоненте), пока грузим их - показываем лоадер, как загрузили - записали в стор и отрендерили страницу.

Пока я вижу так: у нас есть специальный компонент Resolver, которому можно передать сервис или объект или функцию, чето такое, что будет загружать данные и возвращать промис. И пока промис не зарезолвился - Resolver будет рисовать лоадер, если зарезолвился - рисует чайлд.

Компонент страницы будет выглядеть как-то так:
```
<Resolver onLoad={editCardLoader}>
   <CardForm />
</Resolver>
```

2024-01-25 00:21 UTC, Danny-Yellow commented on frontend/src/components/business/Card/Card.tsx
> +        <TextareaAutosize
Забыл спросить, как сделать текстарию. Если ее сделать по размеру карточки,  тогда текст будет в левом верхнем углу, а если задать ей определенную высоту для отцентровки, то уже на второй строке будет скрол

2024-01-25 02:37 UTC, norvele commented on frontend/src/components/business/Card/Card.tsx
> +        <TextareaAutosize
да, точно, не подумал. Тогда варианта два
1) оставить автовысоту, просто ограничить ее размером карточки
2) юзать contenteditable

2024-01-25 03:41 UTC, Danny-Yellow commented on frontend/src/components/business/Card/Card.tsx
> +        <TextareaAutosize
Ну а для contenteditable мы не сможем задать placeholder

2024-01-25 08:49 UTC, norvele commented on frontend/src/components/business/Card/Card.tsx
> +        <TextareaAutosize
да костылями можно, но скорее всего не стоит того

2024-01-27 09:18 UTC, Danny-Yellow commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
> +  const [newCard, setNewCard] = useState<ICard>({
Как ты сказал, сделать не получилось, поэтому заюзал запросы recoil. Щас всё нормально работает.
Только не знаю, как потом обрабатывать другие методы http, в доке ничего про это не нашел

2024-01-28 14:00 UTC, norvele requested changes

2024-01-28 14:00 UTC, norvele commented on frontend/src/API/ApiService.ts
> +  static async fetching(
1. Надо сделать не статичный метод, а обычный метод экземпляра, экземпляр нужно будет гдето рядом с точкой входа приложения создать и посмотреть как его прокинуть в рекойл, чтобы использовать. Экземпляр нужен т.к. мы собираемся конфигурировать этот сервис (например сетить туда авторизационный токен с которым он будет делать запросы)
PS В будущем я думаю можно заиспользовать inversify, чтобы удобно работать с зависимостями, но пока избыточно.
2. Методы\функции лучше называть глаголом, тут например fetch будет. Типо что сделать - зафетчить, а не фетчение )
3. Лучше этот метод сделать protected и сделать public методы get, post, patch, delete, которые в аргументах будут принимать только то чо им нужно. Надо стремиться чтобы паблик методы были специализированными, а не абстрактными. Так более точные типы можно писать и меньше ошибок будет, да и интерфейс для тех кто взаимодействует с классом будет проще.

2024-01-28 14:00 UTC, norvele commented on frontend/src/API/ApiService.ts
> +    const response = fetch(`${url}`, options);
тут не response, тут промис, можно return fetch(`${url}`, options); написать прост

2024-01-28 14:00 UTC, norvele commented on frontend/src/components/business/CardEditor/CardEditor.tsx
> +  setHasError: SetterOrUpdater<boolean>;
Компонент не должен устанавливать ошибку, это не его обязанность. Ошибка должна считаться в сторе где бизнес логика

2024-01-28 14:00 UTC, norvele commented on frontend/src/components/business/CardEditor/CardEditor.tsx
> +  const [inputValue, setInputValue] = useState({ front: '', back: '' });
этот стейт не нужен т.к. это должно быть в сторе

2024-01-28 14:00 UTC, norvele commented on frontend/src/components/business/CardEditor/CardEditor.tsx
> +      <SidePanel onSwitchChange={toggleSwitch} side={side} />
выглядит так что можно написать onSwitchChange={setSide} а toggleSwitch убрать

2024-01-28 14:00 UTC, norvele commented on frontend/src/components/business/CardEditor/CardEditor.tsx
> +  function onFocusHandler() {
это не нужно, ошибка считается в сторе постоянно на любое изменение текста. Показываем мы ее при нажатии кнопки submit

2024-01-28 14:00 UTC, norvele commented on frontend/src/components/business/CardEditor/CardEditor.tsx
> +    setInputValue({ ...inputValue, [side]: event.target.value });
setInputValue не нужен, т.к. стэйт в сторе. Дублировать стор ненадо, будут ошибки. Поток данных должен быть однонаправленным
user change input value -> call callback -> change store data
store data -> input value

2024-01-28 14:00 UTC, norvele commented on frontend/src/components/business/CardForm/CardForm.tsx
> +  const setModal = useSetRecoilState(modalState);
Не нравится что мы для вызова модалки должны знать стор и апдейтить его на "низком" уровне. Давай создадим свой кастомный хук (у нас это называлось композицией), это просто ts файл `export function useModal() {...}` где будут методы для вызова модалки и скрытия.

Использовать так:
```
const { showModal, hideModal } = useModal()
showModal('myModalName', params) // или передавать объект типа { name: 'myModalName', params } чтобы смочь протипизировать параметры для каждой модалки
```

2024-01-28 14:00 UTC, norvele commented on frontend/src/components/business/CardForm/CardForm.tsx
> +    setModal('confirm');
Хочется сразу предусмотреть проброс параметров для модалки. Например для confirm это будет текст, текст на кнопке целевого действия, кэлбэк который вызовется при нажатии этой кнопки. Чтобы сделать confirm модалку абстрактной и чтобы ее можно было бы использовать в других местах ничо не меняя

2024-01-28 14:00 UTC, norvele commented on frontend/src/components/business/CardForm/CardForm.tsx
> +  const setModal = useSetRecoilState(modalState);
Вообще по хорошему надо сразу заложить слой хуков\композиции, который будет между компонентами и сторами. Т.е. компонент (даже hoc) не ходит напрямую в стор, он идет в хук, а хук в стор. При этом 1 хук например может ходить в разные сторы

2024-01-28 14:00 UTC, norvele commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
> +    setHasError(false);
вот какраз если в сторе ошибка будет вычисляться автоматом - нам не придется по всему коду распихивать эти setHasError(false);, всеравно какоенить место да забудешь. Надо стремиться чтобы все было декларативно, сейчас императивно

2024-01-28 14:00 UTC, norvele commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
> +const CreateCardPage = () => {
Предлагаю много логики отсюда вынести в кастомный хук\кмопозицию

2024-01-28 14:00 UTC, norvele commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
> +    setHasError(false);
эту логику кстати после этого можно будет заиспользовать для EditCardPage

2024-01-28 14:00 UTC, norvele commented on frontend/src/store/cardsStore.ts
> +  get: async () => {
чето не нравится мне этот подход, никакого контроля над тем  в какой момент начинать запрос. И как вообще обновлять данные? ну вот я загрузил список карточек, мне надо его перезагрузить чтобы отфильтровать или еще чето сделать, дичь какаято, кто ваще это придумал и зачем

2024-01-28 14:00 UTC, norvele commented on frontend/src/components/business/ConfirmModal/ConfirmModal.tsx
> +  const text: string = 'Are you sure you want to delete this card?';
Вот мы либо называем эту модалку не confirmModal а confirmCardDeletionOnCardPageModal, либо делаем абстрактной, чтобы можно было при ее открытии передавать параметры с текстом и т.д. Я бы выбрал второй вариант, также тут поюзать хук useModal, чтобы вытаскивать параметры для модалки и закрывать ее тут

PS я бы в каждый метод этого хука бы первым аргументом передавал название модалки, для hideModal тоже, чтобы если мы решим что у нас может быть открыто одновременно несколько модалок - это легко можно было сделать поправив только хук модалок и стор, не трогая компоненты

2024-01-28 14:00 UTC, norvele commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
> +  function saveHandler() {
это прямо целиком в сторе должно быть

2024-01-31 07:46 UTC, Danny-Yellow commented on frontend/src/components/business/CardEditor/CardEditor.tsx
> +  setHasError: SetterOrUpdater<boolean>;
Не понимаю как ошибка может считаться в сторе. Ладно в редаксе можно через экшены обращаться к состояниям и изменять их на основе какой-то логики, но как это сделать в recoil, когда у нас нет этих экшенов. Типо просто в сторе через useRecoil это всё делать, но как-то это странно + у это нужно 3 разных обращения, т.к. стэйты в разных атомах

2024-01-31 07:56 UTC, Danny-Yellow commented on frontend/src/components/business/CardForm/CardForm.tsx
> +  const setModal = useSetRecoilState(modalState);
Окей, но по-моему это будет не хук, а что-то другое. Опять же такое ощущение, что это какие-то экшены для взаимодействия со стором. Есть какой-нибудь пример композиции?

2024-02-01 11:35 UTC, Danny-Yellow commented on frontend/src/store/cardsStore.ts
> +  get: async () => {
не знаю, как это по-другому сделать

2024-02-01 12:48 UTC, Danny-Yellow commented on frontend/src/store/cardsStore.ts
> +  get: async () => {
Вообще для обновления есть useRecoilRefresher(), можешь почитать доку

2024-02-08 04:03 UTC, norvele requested changes

2024-02-08 04:03 UTC, norvele commented on frontend/src/API/CardApiService.ts
> +interface IOptions {
IOptions, IApiService вынеси в отдельный файл например types.ts в папке API
и переиспользуй в ApiService тоже

2024-02-08 04:03 UTC, norvele commented on frontend/src/API/CardApiService.ts
> +  protected ApiService: IApiService;
принято классы называть с большой буквы, а экземпляры с маленькой, чтобы не путаться, тут будет apiService

2024-02-08 04:03 UTC, norvele commented on frontend/src/API/index.ts
Этот файл будет 1 на весь проект, лучше положи его в корень и назови чето типо container.ts

2024-02-08 04:03 UTC, norvele commented on frontend/src/API/index.ts
т.е. тут будут вообще все сервисы проекта инитаться

2024-02-08 04:03 UTC, norvele commented on frontend/src/API/CardApiService.ts
> +interface IOptions {
можешь в папку types положить кстати

2024-02-08 04:03 UTC, norvele commented on frontend/src/types/Modal.ts
> +export interface IModalParams {
тут начнутся проблемы как только мы добавим еще 1 вид модалки. Скорее всего нам нужно будет связать name и параметры модалки типа так
```
interface ConfirmationModal {
  name: 'confirmation';
  params: {
    notification: string;
    // ...
  }
}

interface ListContextModal {
  name: 'listContext';
  params: { /*...*/ }
}

type IModal = ConfirmationModal | ListContextModal 
```

в showModal() мы будем принимать не name и параметры а все вместе
`showModal({ name: 'confirmation', params: {/*...*/} })`
так у нас будут жесткие типы, которые не дадут для модалки вкинуть левые параметры

есть еще 1 вариант как сделать но я в нем не до конца уверен, надо проверить, что-то типа
```
type ModalName = 'confirmation' | 'listContext';
type ModalParams = {
  confirmation: {
    notification: string;
    // ...
  },
  listContext: { /*...*/ },
} satisfies { [modalName]: any }

showModal<M extends ModalName>(name: M, params: ModalParams[M])
```
поидее эффект будет тотже, будет ошибка типа если мы попытаемся вызвать модалку не с теми параметрами которые ей нужны

2024-02-13 07:49 UTC, norvele requested changes

2024-02-13 07:49 UTC, norvele commented on frontend/src/hooks/useModal.ts
> +    switch (modal.name) {
это совсем плохо, нарушение буквы O из солида. Мы нигде не должны перебирать вот так что-либо

2024-02-13 07:49 UTC, norvele commented on frontend/src/hooks/useModal.ts
> +    switch (modal.name) {
раньше же было нормально все, нам просто типы надо было переделать

2024-02-13 07:49 UTC, norvele commented on frontend/src/store/modalStore.ts
> +export const confirmationModalState = atom({
стэйт должен быть один на все модалки

2024-02-13 07:49 UTC, norvele commented on frontend/src/types/modal.d.ts
> +  name: 'confirmation' | '';
зачем тут пустая строка? это в TModal создаст кривой тип с name="" и любым params

2024-02-13 07:49 UTC, norvele commented on frontend/src/types/modal.d.ts
> +  name: 'confirmation' | '';
Если нужно для скрытия модалки то это не тут должно описываться, а там где логика этого скрытия, в стэйте чето типо openedModal: undefined | TModal, ну или "" | TModal

2024-02-13 07:49 UTC, norvele commented on frontend/src/store/modalStore.ts
> +export const confirmationModalState = atom({
чето типа
```
export const listContextModalState = atom({
  key: 'openedModal',
  default: {
    name: '',
    params: {},
  } as TModal,
});
```

2024-02-13 07:49 UTC, norvele commented on frontend/src/App.tsx
> +  switch (currentModal) {
у нас есть тип TModalName, давай сделаем мапу Record<TModalName, ReactNode> и уберем свич

2024-02-13 11:19 UTC, norvele approved these changes

2024-02-13 11:49 UTC, merged