start of migration
norvele/cardkeeper pull request #8
Opened 2024-02-15 11:51 UTC by Danny-Yellow

2024-02-25 05:45 UTC, Danny-Yellow commented on frontend/src/services/CardFormService.ts
> +}
Может это все-таки оставить в хуках, чтобы понимать, что эти методы мы можем использовать только на верхнем уровне компонента

2024-02-25 05:45 UTC, Danny-Yellow commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
> +      cardFormService.resetCardForm();
Тут виден ресет формы до того как происходит редирект на другую страницу. Хз пока как исправить

2024-02-25 05:45 UTC, Danny-Yellow commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
>    function goBackHandler() {
Как себя должна вести эта функция, если вызвать ее во время асинхронного сохранения карточки?
Нужно отменить запрос?

2024-02-25 11:33 UTC, norvele commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
> +      cardFormService.resetCardForm();
я бы форму ресетил в момент когда мы на нее заходим, а не наоборот. Просто выйти с формы можно миллионом способов, все не покроем же

2024-02-25 11:33 UTC, norvele commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
>    function goBackHandler() {
В идеальном мире да, но обычно все на это забивают т.к. сложно )

2024-02-25 11:43 UTC, norvele requested changes

2024-02-25 11:43 UTC, norvele commented on frontend/src/store/cardFormStore.ts
> +export const saveCardFx = createEffect<
Короче выглядит так что либо это все должно быть в сервисе, запросы все из сервиса делаются, а стором мы управляем тока ивентами\методами. Но так мы по сути выкинем больше половины апи эффектора, включая удобности типо подписок на всякие failData, doneData и т.д.

А так щаз апи эффектора нас принуждает бизнес логику держать в нем (как я понял это его мейн фича). Поэтому я склоняюсь к тому чтобы сервисы упразднить вообще (кроме api сервисов) и БЛ делать в эффекторе. Походу даже слой композиций не сильно то и нужен будет кек

2024-02-25 11:43 UTC, norvele commented on frontend/src/services/CardFormService.ts
> +}
Сервисы походу с эффектором не нужны даже

2024-02-27 12:45 UTC, Danny-Yellow commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
>    function goBackHandler() {
А просто с помощью контроллера это нельзя сделать?

2024-02-27 12:49 UTC, Danny-Yellow commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
> +  const [cardSide, setCardSide] = useState<'front' | 'back'>('front');
useState для того, чтобы при заходе на страницу переключатель сразу стоял на своем месте, и не было анимации переключения

2024-02-28 04:55 UTC, norvele requested changes

2024-02-28 04:55 UTC, norvele commented on frontend/src/pages/CreateCardPage/CreateCardPage.tsx
> +  const [cardSide, setCardSide] = useState<'front' | 'back'>('front');
Мы просто не должны рендерить пока все не подготовим, по хорошему всю страницу мы не должны рендерить. 
На каждой странице будет какой-то асинхронный кэлбэк (который приводит стор в какое-то начальное состояние, грузит нужные данные и т.д.), он будет дергаться и пока он не исполнится - рендера не должно быть.

Иначе помимо cardSide у нас в скором времени появятся еще штуки и мы поитогу задублируем стор в компоненты. Надо избегать хранение стейта в компонентах тем более что в сторе это уже есть.

2024-02-28 04:55 UTC, norvele commented
В остальном збс

2024-02-28 10:30 UTC, norvele approved these changes

2024-02-28 11:58 UTC, merged